### ISSUE TITLE
Missing submodules

### ISSUE THREAD

**Issue by eliottness** [ourfavoritefruits/yuzu#1]
If you happen to have them. Please create repos for the submodules of yuzu, upload them and fix the url of the submodules

**Comment by animeavi** [comment]
Here's the list, anyone that had a fully cloned repo (as in, used --recurse-submodules), can help restore those.

- https://github.com/yuzu-emu/discord-rpc
(located in externals/discord-rpc)

- https://github.com/yuzu-emu/sirit
(located in externals/sirit)

- https://github.com/yuzu-emu/mbedtls
(located in externals/mbedtls)

- https://github.com/yuzu-emu/breakpad
(located in externals/breakpad)

**Comment by ourfavoritefruits** [comment]
Yeah, sorry.
It should compile now.
